spring.application.name=enterprise-billing-payment-platform
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/billing_db}
spring.datasource.username=${DB_USERNAME:billing_user}
spring.datasource.password=${DB_PASSWORD:billing_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

payment.gateway.razorpay.key-id=${RAZORPAY_KEY_ID:}
payment.gateway.razorpay.key-secret=${RAZORPAY_KEY_SECRET:}

payment.gateway.razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}

reconciliation.scheduler.cron=0 0 14 * * *
reconciliation.scheduler.zone=Asia/Kolkata

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.shaqib.billing.notification.event
spring.kafka.consumer.auto-offset-reset=earliest


spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.retry.delay-ms=${NOTIFICATION_RETRY_DELAY_MS:60000}