spring.application.name=enterprise-billing-payment-platform
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/billing_db}
spring.datasource.username=${DB_USERNAME:billing_user}
spring.datasource.password=${DB_PASSWORD:billing_password}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

payment.gateway.razorpay.key-id=${RAZORPAY_KEY_ID:}
payment.gateway.razorpay.key-secret=${RAZORPAY_KEY_SECRET:}

payment.gateway.razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET:}

reconciliation.scheduler.cron=0 0 14 * * *
reconciliation.scheduler.zone=Asia/Kolkata